name: mathsticks
description: "A new Flutter project."
publish_to: 'none'


version: 1.2.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_joystick: ^0.2.1
  audioplayers: ^5.2.1
  flutter_tts: ^3.8.5 
  just_audio: ^0.9.42
  async: ^2.9.0
  shared_preferences: ^2.2.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/Palito V.png
    - assets/images/Palito H.png
    - assets/images/Palito DD.png
    - assets/images/Palito DE.png
    - assets/images/pulare.png
    - assets/images/pulard.png
    - assets/images/pularc.png
    - assets/images/pularb.png
    - assets/images/ponto.png
    - assets/images/personagem.png
    - assets/sounds/baixo.mp3
    - assets/sounds/cima.mp3
    - assets/sounds/direita.mp3
    - assets/sounds/esquerda.mp3
    - assets/sounds/palitoDiagonalDireita.mp3
    - assets/sounds/palitoDiagonalEsquerda.mp3
    - assets/sounds/palitoHorizontal.mp3
    - assets/sounds/palitoVertical.mp3 
    - assets/images/IFSP_Logo.png
    - assets/images/CNPQ_Logo.png
    - assets/images/RUMO_Logo.png
   
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

  